development:
  adapter: postgresql
  database: happycal_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: happycal_devolopment

production:
  adapter: postgresql
  database: happycal_development
